//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracSoforleri
    {
        public int servisSoforId { get; set; }
        public int aracId { get; set; }
        public int sofId { get; set; }
        public bool yedekMi { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Soforler Soforler { get; set; }
    }
}
