//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duraklar
    {
        public int durakId { get; set; }
        public int rotaId { get; set; }
        public int ogrId { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Rotalar Rotalar { get; set; }
    }
}
