//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.FirmaServisleri = new HashSet<FirmaServisleri>();
            this.FirmaSoforleri = new HashSet<FirmaSoforleri>();
        }
    
        public int firId { get; set; }
        public string firAd { get; set; }
        public string firEmail { get; set; }
        public string firParola { get; set; }
        public string firYetkiliAdSoyad { get; set; }
        public string firTel { get; set; }
        public string firFax { get; set; }
        public string firAdres { get; set; }
        public int ilce_id { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaServisleri> FirmaServisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaSoforleri> FirmaSoforleri { get; set; }
    }
}
