//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaAraclari
    {
        public int firmaAracId { get; set; }
        public int firId { get; set; }
        public int aracId { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Firmalar Firmalar { get; set; }
    }
}
