//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiBindiler
    {
        public int indiBindiId { get; set; }
        public int servistekiOgrenciId { get; set; }
        public System.DateTime bindiTarihi { get; set; }
        public System.DateTime indiTarihi { get; set; }
        public int okuldanEveEvdenOkula { get; set; }
    
        public virtual ServistekiOgrenciler ServistekiOgrenciler { get; set; }
    }
}
