//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mudurler
    {
        public int mudurId { get; set; }
        public string mudurAd { get; set; }
        public string mudurSoyad { get; set; }
        public string mudurParola { get; set; }
        public string mudurTelefon { get; set; }
        public string mudurEmail { get; set; }
        public int okulId { get; set; }
    
        public virtual Okullar Okullar { get; set; }
    }
}
