//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int odemeId { get; set; }
        public int faturaId { get; set; }
        public System.DateTime odemeTarihi { get; set; }
        public decimal miktar { get; set; }
    
        public virtual Faturalar Faturalar { get; set; }
    }
}
