//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Duraklar = new HashSet<Duraklar>();
            this.Faturalar = new HashSet<Faturalar>();
            this.OgrenciVelileri = new HashSet<OgrenciVelileri>();
            this.ServistekiOgrenciler = new HashSet<ServistekiOgrenciler>();
        }
    
        public int ogrId { get; set; }
        public long ogrTCno { get; set; }
        public string ogrAd { get; set; }
        public string ogrSoyad { get; set; }
        public string ogrAdres { get; set; }
        public string ogrGsm { get; set; }
        public int okulId { get; set; }
        public int ogrenciNo { get; set; }
        public int ilce_id { get; set; }
        public string geoX { get; set; }
        public string geoY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duraklar> Duraklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        public virtual Ilceler Ilceler { get; set; }
        public virtual Okullar Okullar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciVelileri> OgrenciVelileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServistekiOgrenciler> ServistekiOgrenciler { get; set; }
    }
}
