//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okullar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Okullar()
        {
            this.Mudurler = new HashSet<Mudurler>();
            this.Ogrenciler = new HashSet<Ogrenciler>();
            this.OkulServisleri = new HashSet<OkulServisleri>();
            this.Rotalar = new HashSet<Rotalar>();
        }
    
        public int okulId { get; set; }
        public string okulAdi { get; set; }
        public string okulAdres { get; set; }
        public string okulTel { get; set; }
        public string okulMail { get; set; }
        public int ilce_id { get; set; }
        public int okulTurId { get; set; }
        public int okulCinsId { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mudurler> Mudurler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenciler> Ogrenciler { get; set; }
        public virtual OkulCinsleri OkulCinsleri { get; set; }
        public virtual OkulTurleri OkulTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OkulServisleri> OkulServisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rotalar> Rotalar { get; set; }
    }
}
