//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServistekiOgrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServistekiOgrenciler()
        {
            this.Faturalar = new HashSet<Faturalar>();
            this.IndiBindiler = new HashSet<IndiBindiler>();
        }
    
        public int servistekiOgrenciId { get; set; }
        public int ogrId { get; set; }
        public int okulServisId { get; set; }
        public System.TimeSpan alimZamani { get; set; }
        public System.TimeSpan teslimZamani { get; set; }
        public decimal ucret { get; set; }
        public System.DateTime kayitTarihi { get; set; }
        public short ogretimTuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndiBindiler> IndiBindiler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual OkulServisleri OkulServisleri { get; set; }
    }
}
