//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servisler()
        {
            this.FirmaServisleri = new HashSet<FirmaServisleri>();
            this.OkulServisleri = new HashSet<OkulServisleri>();
            this.ServisSoforleri = new HashSet<ServisSoforleri>();
        }
    
        public int servisId { get; set; }
        public string plaka { get; set; }
        public Nullable<System.DateTime> sonMuayeneTarih { get; set; }
        public Nullable<System.DateTime> iseGirisTarih { get; set; }
        public int sicilNo { get; set; }
        public bool aktifMi { get; set; }
        public string authCode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaServisleri> FirmaServisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OkulServisleri> OkulServisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisSoforleri> ServisSoforleri { get; set; }
    }
}
