//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veliler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veliler()
        {
            this.OgrenciVelileri = new HashSet<OgrenciVelileri>();
        }
    
        public int veliId { get; set; }
        public string veliAd { get; set; }
        public string veliSoyad { get; set; }
        public string veliEmail { get; set; }
        public string veliParola { get; set; }
        public string veliGsm { get; set; }
        public string veliAdres { get; set; }
        public int ilce_id { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciVelileri> OgrenciVelileri { get; set; }
    }
}
